### PR TITLE
Add a very basic search page

### PR DESCRIPTION
**Pull request by octopusinvitro**
screen shot 2017-02-17 at 17 02 17

^ screenshot by @zarino :smiley:

### CODE REVIEW

**Comment by zarino** [comment]
@octopusinvitro Gimme 15 minutes now and I'll sort it out.

**Comment by octopusinvitro** [comment]
@zarino to make your life easier, I added this:
```css

.site-body__search-container {
  max-width: 30em;
  margin: auto;
}
```
in the `_site-header.scss` file

**Comment by mhl** [comment]
@octopusinvitro There's a waring that it would be good to fix:

/home/mark/mysociety/shineyoureye-sinatra/app.rb:120: warning: already initialized constant Search
/home/mark/mysociety/shineyoureye-sinatra/app.rb:120: warning: previous definition of Search was here

**Comment by zarino** [comment]
@octopusinvitro – I'm done!

**Comment by octopusinvitro** [comment]
@mhl Feedback addressed. The `Struct` had to be outside of the route :boom:

**Pull request merged**
