### PR TITLE
Update the Senator dataset from the concluded election

### PR DESCRIPTION
**Pull request by EiEResearch**
This PR needs to update the records on the website. this is achieved by updating the csv data. Existing unit testing conditions were modified to reflect the new dataset. total of 6 commits in this PR, mostly back and fort with why tests were passing on my machine and failing at CI level.

Not Applicable

only errors relating to encoding were being reported. I could have the post body enforce the use of a character encoding. By the way, I am running this app on a Windows machine, line endings would be different. Lets see if it passes travisCI test.

test_outcome

### CODE REVIEW

**Comment by EiEResearch** [comment]
@chrismytton Most of the test suites on your repo do not apply if i do a massive data change. I have rewritten applicable test criterias for each instance that relates to the new data. How do we reconcile this.

**Comment by EiEResearch** [comment]
@chrismytton would you mind taking a look at this in the interim.

**Comment by EiEResearch** [comment]
> Looks good to me! 👍
> 
> Great work figuring this all out, especially getting the tests passing with the updated data!

I see you have given collaborator access to eieresearch. I am only on this project for the next 6months. This means i have read and write access, do i still need to create PRs or I just push and let travis take care of the rest?

**Comment by EiEResearch** [comment]
> > Looks good to me! 👍
> > Great work figuring this all out, especially getting the tests passing with the updated data!
> 
> I see you have given collaborator access to eieresearch. I am only on this project for the next 6months. This means i have read and write access, do i still need to create PRs or I just push and let travis take care of the rest?

I also do not have access to this repo build history on TravisCI, i do not know what happens next when a PR is merged in, or how long for the files to be updated.

**Comment by chrismytton** [comment]
> I see you have given collaborator access to eieresearch. I am only on this project for the next 6months. This means i have read and write access, do i still need to create PRs or I just push and let travis take care of the rest?

Up to you. If you're not confident in a change then feel free to make a pull request and request a review from me and I'll take a look. Otherwise you can either create pull requests (so you have a log of what's been done) and then merge them yourself without a review, or just push directly to the master branch.

> I also do not have access to this repo build history on TravisCI, i do not know what happens next when a PR is merged in, or how long for the files to be updated.

I'm not sure how Travis decides who has access, I thought it was all based on GitHub. You might need to log out of Travis and log back in using your GitHub account.

**Pull request merged**
